name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Checks

    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        preset: node
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: yarn
    - run: yarn --frozen-lockfile
    - run: yarn test
    - run: yarn lint
